name: dsnd-webdev
channels:
    - https://conda.anaconda.org/menpo
    - conda-forge
dependencies:
    - python==3.6.1
    - pip
    - pip:
        - numpy
        - matplotlib
        - pandas
        - scikit-learn
        - flask
        - plotly
